FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /build

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

EXPOSE 9080

ENTRYPOINT ["java", "-XX:+UseG1GC", "-jar", "app.jar"]